### ISSUE TITLE
Reconnections creates multiple messages

### ISSUE THREAD

**Issue by blacksun1** [sdelements/hubot-lets-chat#14]
If you leave the hubot running but close and re-run Lets-Chat (Ctrl+c to shut it down and re-run it again) when running a hubot command it will then return 2 messages.

This will continue to add an extra message if this is continued. Running this on Mac OS-X, Nodejs v1.4.1 and a bog standard yeoman created hubot.

I'm guessing that it should be closing something down, somewhere but it isn't.

**Comment by hhaidar** [comment]
@blacksun1 thanks! should be fixed now if you update to 0.0.6 :)

**Comment by blacksun1** [comment]
Fantastic. Works a treat.

**Comment by blacksun1** [comment]
:beers: :beers: :beers: :beers: :beers: :beers:
