### ISSUE TITLE
API to add new rooms or the auth token

### ISSUE THREAD

**Issue by rawlingsj** [sdelements/hubot-lets-chat#15]
Hi, is there an api to add Lets Chat rooms and and the Auth token rather than setting the env vars `HUBOT_LCB_TOKEN` and `HUBOT_LCB_ROOMS`?

The use case would be to add new rooms to the adaptor after they've been added in Lets Chat.  Currently the only way I can see is to set a new `HUBOT_LCB_ROOMS` and restart hubot.

**Comment by rawlingsj** [comment]
Is this something that could be addressed in this project or is it more a hubot issue?  I'm just getting to grips with hubot but happy to have a crack at it if someone has a good starting point.

**Comment by hhaidar** [comment]
This falls under a hubot issue. You could probably try writing a script that joins rooms. The difficult part would be getting the script talking to the socket io instance in the adapter.

I'm not sure if there's a hubot sanctioned way to do rooms. If there is, that might simplify things.

**Comment by rawlingsj** [comment]
Ok thanks @hhaidar, I'll have a dig around and see if there's a right way with hubots.  I'll add a comment to this issue if I find anything.

**Comment by hhaidar** [comment]
Cool, lemme know if we can help in any way.
