### ISSUE TITLE
Unable to set up with local let's chat instance

### ISSUE THREAD

**Issue by depinav** [sdelements/hubot-lets-chat#7]
Im trying to get this working with a locally running instance of let's chat. The instructions in the readme aren't very helpful though. For instance, I installed hubot, but the `hubot --create myhubot` command doesn't work, I had to use yo hubot like the hubot readme mentions. Then the instructions here mention adding the env vars for the different version of let's chat, but Im not entirely sure where to add them.

**Comment by hhaidar** [comment]
If you're new to Let's Chat, you're running 0.3.x. So you only need `HUBOT_LCB_TOKEN` and `HUBOT_LCB_ROOMS`

To set these environment variables, you can just use the export commands like:

```
export HUBOT_LCB_TOKEN=TOKEN (this is in dropdown of your user account under 'Auth Tokens')
export HUBOT_LCB_ROOMS=ROOMID,ROOMID,etc..
```

If you're running windows you can do [something like this](https://kb.wisc.edu/cae/page.php?id=24500). I should mention that windows might be a little flaky though.

It's strange that `--create` did not work. What version of hubot do you have? Try running `hubot --help` and see if you get something like this:

```
(sdlc)mac-attack:sigma houssam$ hubot --version
2.6.0
(sdlc)mac-attack:sigma houssam$ hubot --help
Usage hubot [options]

Available options:
  -a, --adapter ADAPTER   The Adapter to use
  -c, --create PATH       Create a deployable hubot
..
```

**Comment by depinav** [comment]
Terminal doesn't recognize hubot as a command. I get `env: coffee: No such file or directory` when I try it. Im on a mac though, should've probably mentioned that initially. Does the `hubot --create` do the same thing that 'yo hubot' does?

**Comment by hhaidar** [comment]
Cool, that's easy to fix! Just install coffee-script via:

```
npm install -g coffee-script
```

And yea, `yo hubot` *should* do what `hubot --create` does. But you can't really run hubot without coffee-script installed :)

**Comment by depinav** [comment]
Cool, yea that all seemed to help (although, when I run `hubot --create` I get a deprecated warning and it advises me to use the yo generator). I'm able to run `./bin/hubot -a lets-chat` and I see logs, the last of which says it's joining the room i added to the env var. The new issue is Im not able to access the bot in the room. Could this be an issue with the token var? Maybe I entered it incorrectly? I appreciate the help btw.

**Comment by sibartlett** [comment]
@depinav you need to create a Let's Chat account specifically for the bot, and generate the token under that account.

@hhaidar we should update the README, and maybe just link to [Hubot's instructions](https://github.com/github/hubot/blob/master/docs/README.md)?

**Comment by depinav** [comment]
@sibartlett You know, that actually makes a whole lot of sense when said aloud. I'll have to give it a shot when I get home. But yea, I would say updating the readme would be great. The info in this thread was immensely helpful so it would probably be a great resource for what to update. Thanks again guys.

**Comment by hhaidar** [comment]
@depinav did you end up getting it to work?

**Comment by depinav** [comment]
@hhaidar Won't be able to try until I get home later this evening. I'll report back when I give it a shot.

**Comment by chriscaddell** [comment]
@hhaidar I followed the instructions, made the token for the bot's account, and ran the startup line above. The bot connects to the chatroom (I can see it's name in the UI), but it never responds when I try to mention it. Here are the command line issues that pop up.

---
connect deprecated multipart: use parser (multiparty, busboy, formidable) npm module instead node_modules/hubot/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:56:20
connect deprecated limit: Restrict request size at location of read node_modules/hubot/node_modules/express/node_modules/connect/lib/middleware/multipart.js:86:15
[Thu Feb 19 2015 13:13:46 GMT-0800 (PST)] ERROR Error: listen EADDRINUSE
  at errnoException (net.js:904:11)
  at Server._listen2 (net.js:1042:14)
  at listen (net.js:1064:10)
  at net.js:1146:9
  at dns.js:72:18
  at process._tickCallback (node.js:419:13)

connected
[Thu Feb 19 2015 13:13:46 GMT-0800 (PST)] ERROR hubot-heroku-alive included, but missing HUBOT_HEROKU_KEEPALIVE_URL. `heroku config:set HUBOT_HEROKU_KEEPALIVE_URL=$(heroku apps:info -s  | grep web_url | cut -d= -f2)`
[Thu Feb 19 2015 13:13:46 GMT-0800 (PST)] INFO Using default redis on localhost:6379

**Comment by hhaidar** [comment]
How do you contact the bot?

it should be `@USERNAME_OF_BOT ping`

**Comment by chriscaddell** [comment]
@hhaidar I did. After turning everything off, then back on again, I managed to get it to work (although the error still displays). I'll consider it working at this point thought :)

**Comment by hhaidar** [comment]
@chriscaddell haha, good to hear. Yea I guess something is up with hubot + heroku. We run a couple of hubots on regular old machines, so I don't really know what's going on. But if it works, it works!

**Comment by depinav** [comment]
@hhaidar @sibartlett Finally got home to testing it. It worked perfectly. Thanks for the help.

**Comment by hhaidar** [comment]
Anytime @depinav!

Let us know if you encounter any issues and maybe drop a bit of code our way sometime :P
