### ISSUE TITLE
Support for enter and leave events

### ISSUE THREAD

**Issue by SleeplessAnnoyedNerd** [sdelements/hubot-lets-chat#9]
Adapter currently doesn't support user *enter*ing or *leav[e]*ing. So if someone wants to use `hubot-tell` (and `hubot-ambush`) it doesn't work.

Following addition (in `0_3.coffee`) works for me, probably not perfect but at least a start. (Tested w/ `hubot-tell`.)

```javascript
EnterMessage = require('hubot').EnterMessage
LeaveMessage = require('hubot').LeaveMessage
...
    @socket.on 'users:join', (data) =>
      user = @robot.brain.userForId data.username,
        room: data.room,
        name: data.username
      @receive new EnterMessage user, null, data.id

    @socket.on 'users:leave', (data) =>
      user = @robot.brain.userForId data.username,
        room: data.room,
        name: data.username
      @receive new LeaveMessage user, null, data.id
```

**Comment by hhaidar** [comment]
Do you mind opening pull request then?

Perhaps we should make it so that leave/join work per connection rather than once per user. Exposing more events is something to think about.

**Comment by SleeplessAnnoyedNerd** [comment]
> Do you mind opening pull request then?

Can do, but will take some time. I always hurt myself w/ `git`. ;)

> Perhaps we should make it so that leave/join work per connection rather than once per user.

Not sure if I understand. (There is only one connection, no?)

> Exposing more events is something to think about.

Probably. :) But at this point in time I'm not sure which events Hubot supports (didn't check yet).

Well, I will close this for now. And will "come back" w/ a PR in the -- hopfully near -- future...
Anyways, if someone needs the functionality he can c&p the snippet anyways for now.
